name: build apk dev
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependecies
        run: yarn install
      - name: build apk release
        run: yarn build:apk
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
            name: release
            path: android/app/build/outputs/bundle/release/app-release.aab
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: Get build artifacts
          uses: actions/download-artifact@v3
          with:
            name: release
        - name: Locate Apk
          run: ls
