name: Codepush Deployment Dev
on:
  push:
    # branches:
    #   - dev
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Install dependency codepush
        run: yarn global add appcenter-cli
      - name: Deploy app to codepush server
        run: appcenter codepush release-react -a Appcenter-Course-Ci-Cd/inflationcalc-1 -d development --token ${{ secrets.APPCENTER_ACCESS_TOKEN}}
  status:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Status deploy codepush
        run: echo "status done"
